In [1]:
import numpy as np

##  查看阵列属性

In [2]:
#查看数组a1的属性
def check(a1):
    print(a1)  
    print("数据类型",type(a1))           #打印数组数据类型  
    print("数组元素数据类型：",a1.dtype) #打印数组元素数据类型  
    print("数组元素总数：",a1.size)      #打印数组尺寸，即数组元素总数  
    print("数组形状：",a1.shape)         #打印数组形状  
    print("数组的维度数目",a1.ndim)      #打印数组的维度数目

In [14]:
A=np.array([[1,-1,1,1,-1,1,0],[-2,-3,-5,0,0,0,0],[1,0,-2,2,-2,0,-1]])
b=np.array([7,8,1]).reshape(3,1)

check(b)
m=3
n=7
for i in range(n):
    if i==4:
        continue
    for j in range(i+1,n):
        if j==4:
            continue
        for k in range(j+1,n):
            if k==4:
                continue
            B=A[:,i:i+1]
            B=np.c_[B,A[:,j:j+1]]
            B=np.c_[B,A[:,k:k+1]]
            print(i+1,j+1,k+1)
            print(B)
            Binv=np.linalg.inv(B)
            print(Binv)
            xx=Binv@b
            print(f'x: {xx}')
            x=[0]*8
            x[i+1]=xx[0,0]
            x[j+1]=xx[1,0]
            x[k+1]=xx[2,0]
            minz=2*x[1]-x[2]+3*x[3]+x[4]-x[5]
            print(x)
            print('minz',minz)
            print('\n\n')



[[7]
 [8]
 [1]]
数据类型 <class 'numpy.ndarray'>
数组元素数据类型： int32
数组元素总数： 3
数组形状： (3, 1)
数组的维度数目 2
1 2 3
[[ 1 -1  1]
 [-2 -3 -5]
 [ 1  0 -2]]
[[ 0.33333333 -0.11111111  0.44444444]
 [-0.5        -0.16666667  0.16666667]
 [ 0.16666667 -0.05555556 -0.27777778]]
x: [[ 1.88888889]
 [-4.66666667]
 [ 0.44444444]]
[0, 1.8888888888888893, -4.666666666666667, 0.4444444444444443, 0, 0, 0, 0]
minz 9.777777777777779



1 2 4
[[ 1 -1  1]
 [-2 -3  0]
 [ 1  0  2]]
[[ 0.85714286 -0.28571429 -0.42857143]
 [-0.57142857 -0.14285714  0.28571429]
 [-0.42857143  0.14285714  0.71428571]]
x: [[ 3.28571429]
 [-4.85714286]
 [-1.14285714]]
[0, 3.285714285714286, -4.857142857142857, 0, -1.1428571428571428, 0, 0, 0]
minz 10.285714285714286



1 2 6
[[ 1 -1  1]
 [-2 -3  0]
 [ 1  0  0]]
[[-0.00000000e+00  5.55111512e-17  1.00000000e+00]
 [-0.00000000e+00 -3.33333333e-01 -6.66666667e-01]
 [ 1.00000000e+00 -3.33333333e-01 -1.66666667e+00]]
x: [[ 1.        ]
 [-3.33333333]
 [ 2.66666667]]
[0, 1.0000000000000004, -3.33333333

LinAlgError: Singular matrix

In [85]:
m=np.shape(a) #返回a的shape
n=np.size(a) #返回a的size
n=np.size(a,axis=0)#返回维度为0的 a的size

## 生成阵列（numpy.ndarray）

In [31]:
a=np.ones(2) #shape(2,)
b=np.zeros((3,2,4)) #shape(3,2,4)
c=np.array([[0,0],[1,0],[0,1]],dtype=np.complex128) #shape(3,2)
d=np.eye(4) #shape(4,4)
e=np.arange(0,4) #shape(4,)
f=np.arange(0,6).reshape(3,2) #shape(3,2)


## 生成矩阵（numpy.matrix）

In [14]:
#只能生成二维
a=np.mat([1,2,3]) #shape(1,3)
b=np.mat([[1,2,3]]) #shape(1,3)
c=np.mat([[1,2,3],[4,5,6]]) #shape(2,3)

## 阵列矩阵转换（ndarray <=> matrix）

In [49]:
#阵列转换为矩阵
a=np.ones((2,2))
b=np.mat(a)

#矩阵转换为阵列
a=np.mat([[1,2,3],[4,5,6]])
b=np.array(a)

## 矩阵乘法

In [65]:
#ndarray
a=np.ones((2,2))
b=np.arange(0,4).reshape(2,2)

#矩阵每个元素相乘
c=a*b
d=np.multiply(a,b) #c==d

#矩阵点乘(矩阵乘法)
e=np.dot(a,b)
f=a@b 
g=a.dot(b) #e==f==g


In [66]:
#matrix
a=np.mat([[1,1],[1,1]])
b=np.mat([[0,1],[2,3]])

#矩阵每个元素相乘
c=np.multiply(a,b) #c!=a*b 与ndarray不同


#矩阵点乘(矩阵乘法)
d=a*b
e=np.dot(a,b)
f=a@b 
g=a.dot(b) #d==e==f==g


## np.random

In [78]:
#生成随机数据
a=np.random.rand(2,3) #shape(2,3) [0,1)均匀分布 
b=np.random.randn(3,2,5) #shape(2,3) 标准正态分布
c=np.random.randint(2,4,(2,3)) #shape(2,3) [low,high)

#shuffle
np.random.shuffle(b) #根据数组a的第1轴（也就是最外层的维度）进行随机排列，改变数组a
d=np.random.permutation(b)#根据数组a的第1轴进行随机排列，不改变数组a，返回一个新的数组

#choice
#从一维数组a中以概率p抽取元素，形成size形状新数组replace表示是否可以重用元素，默认为False
e=np.random.choice(b[0][0], size=(1,4), replace=True, p=[0,0,0,0.8,0.2])



[-0.20403972  1.0790322  -0.11728032 -0.06427157 -1.36300841]
数据类型 <class 'numpy.ndarray'>
数组元素数据类型： float64
数组元素总数： 5
数组形状： (5,)
数组的维度数目 1
[[-1.36300841 -0.06427157 -0.06427157 -0.06427157]]
数据类型 <class 'numpy.ndarray'>
数组元素数据类型： float64
数组元素总数： 4
数组形状： (1, 4)
数组的维度数目 2


## 暂未归类

In [ ]:


np.exp(-inx)
np.log10(255.0 / rmse)
np.tanh(0.5 * inx)
np.random.
np.random.multivariate_normal(means0, [[variance, cov], [cov, variance]], number0)
np.random.shuffle(data)
np.random.randint(0, high=N)
mus[i]=np.random.rand(K,aft_dim)


np.sum()
np.sqrt()
acc=np.mean(correct_prediction)


data_test_labels=np.squeeze(data_test_labels)
correct_prediction = np.equal(classes,data_test_labels)



all_data=np.c_[data_scale,label]
data_classj=all_data[np.where(all_data[:,-1]==0)]
#拿到类别为j的数据
data_classj=all_data[np.where(all_data[:,-1]==j)]


min_d = np.argsort(eigenvalues)#输出特征值从小到大的序号排序
feature_vectors = np.delete(feature_vectors, min_d[:columns - reduced_dimension], axis=1)#删除特征值最小所对应特征向量的几列
np.delete(data, -1, axis=1)


np.linspace
np.polyval
np.linalg.norm(data[i,:] - center[j,:])



arg = np.argmin(distance) # the index of the min of distance
argmaxs = np.argmax(gammas, axis=1)
max_arr=np.max(data,axis=0)
min_arr=np.min(data,axis=0)



np.uint8(img_data)

data=pd.read_csv("Skin_NonSkin.txt",sep='\t',header=None)
data=shuffle(data)
data.iloc[:,[3]]=data.iloc[:,[3]].apply(lambda x:x-1)
print(data.iloc[0:10])

In [27]:
a=np.ones((3,2))
b=np.ones((2,1))
m,n=a.shape
print(m,n)
print(a@b)

3 2
[[2.]
 [2.]
 [2.]]
